spring.application.name=Order Service
server.port=9001

spring.datasource.url=jdbc:mysql://localhost:3306/shoppingcart
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

